version: 2.1

workflows:
  main:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master

orbs:
  node: circleci/node@1.1.4

executors:
  node12:
    docker:
      - image: circleci/node:12

commands:
  npm-ci:
    steps:
      - node/with-cache:
          cache-key: package-lock.json
          steps:
            - run: npm ci

jobs:

  test:
    executor: node12
    working_directory: trigger-pipeline
    steps:
      - checkout
      - npm-ci

      - run:
          command: npm run prettier
          when: always

      - run:
          command: npm run typecheck
          when: always

      - run:
          command: npm test -- --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - run:
          command: npm run build
          when: always
      - store_artifacts:
          path: action.bundle.js

  publish:
    executor: node12
    working_directory: trigger-pipeline
    steps:
      - checkout
      - npm-ci
      - run: npm run build
      - run: cat action.bundle.js
      - store_artifacts:
          path: action.bundle.js
