name: "Main"
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: trigger-pipeline
    - run: npm run prettier
      working-directory: trigger-pipeline
    - run: npm run typecheck
      working-directory: trigger-pipeline
    - run: npm test
      working-directory: trigger-pipeline
    - run: npm run build
      working-directory: trigger-pipeline
    - name: "publish code"
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/work-in-progress'
      run: |
        echo TODO - commit and push to a "latest" or otherwise versioned branch
